import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainHeader from "./components/MainHeader";
import { getNextAuthSession } from "@/lib/nextauthSession/session";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/db/prismaDB";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const session = await getNextAuthSession();
    if (!session) {
        redirect("/api/auth/signin");
    }
    const { id } = session.user;

    const user = await prisma.user.findUnique({
        where: { id },
    });
    if (!user) redirect("/api/auth/signin");

    return (
        <html lang="en" className="h-full" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-light-background dark:bg-dark-background`}
            >
                <ThemeProvider attribute={"class"} enableSystem defaultTheme="system">
                    <div className="flex flex-col h-full">
                        <MainHeader userId={id} name={user.name} />
                        <div className="flex-1 px-2 md:px-6 min-h-0">{children}</div>
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
